# App "patrulha" -- khepera4toolbox
# Compilar no robo:  cd /home/root/khepera4toolbox/app/patrulha && make

# Modulos padrao necessarios
MODULES := khepera4 commandline i2cal

# Nome do executavel
TARGET := patrulha

# Raiz do toolbox (no robo)
K4_ROOT := /home/root/khepera4toolbox

# Inclui o sistema de build do toolbox
include $(K4_ROOT)/app/Makefile.include
